name: seytim_staj
description:
publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:

  firebase_auth: ^5.3.4
  firebase_core: any
  firebase_auth_web: ^5.13.5
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  flutter:
    sdk: flutter
  intl: ^0.20.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
