name: seytim_staj
description:
publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  async: any
  characters: any
  collection: ^1.19.0
  firebase_auth: ^5.3.4
  firebase_core: any
  firebase_auth_web: ^5.13.5
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  google_maps_flutter: ^2.10.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  flutter:
    sdk: flutter
  intl: ^0.20.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/twoflower.jpg
    - assets/images/cocukatolye.jpeg
    - assets/images/flowers.webp
    - assets/images/yardımatolye.jpeg
    - assets/images/yogaatolye.jpeg
    - assets/images/woman.jpeg
    - assets/images/backgrflower.jpeg
    - assets/images/golf.jpeg
    - assets/images/sanat.jpeg
    - assets/images/ANNECOCUK.jpeg
    - assets/images/tek.jpeg

  uses-material-design: true
