// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU10BO9_IQcT19GmmZnMVSypQBavQHMww',
    appId: '1:139424585343:web:db9f2ea4b9ed13753b514a',
    messagingSenderId: '139424585343',
    projectId: 'seytimstaj',
    authDomain: 'seytimstaj.firebaseapp.com',
    storageBucket: 'seytimstaj.firebasestorage.app',
    measurementId: 'G-GEDNWGD2KY',
  );




  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiYUdv5ezdlPPQa5eSuv6T_ZWYr02t9Q',
    appId: '1:139424585343:android:cd60b0e690696bb33b514a',
    messagingSenderId: '139424585343',
    projectId: 'seytimstaj',
    storageBucket: 'seytimstaj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6e0fnQHrya3XKC8Np1HCGjz7Vu1biJM',
    appId: '1:139424585343:ios:02e8da9db9f0a2713b514a',
    messagingSenderId: '139424585343',
    projectId: 'seytimstaj',
    storageBucket: 'seytimstaj.firebasestorage.app',
    iosBundleId: 'com.example.seytimStaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF6e0fnQHrya3XKC8Np1HCGjz7Vu1biJM',
    appId: '1:139424585343:ios:02e8da9db9f0a2713b514a',
    messagingSenderId: '139424585343',
    projectId: 'seytimstaj',
    storageBucket: 'seytimstaj.firebasestorage.app',
    iosBundleId: 'com.example.seytimStaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU10BO9_IQcT19GmmZnMVSypQBavQHMww',
    appId: '1:139424585343:web:56460bc631d303b03b514a',
    messagingSenderId: '139424585343',
    projectId: 'seytimstaj',
    authDomain: 'seytimstaj.firebaseapp.com',
    storageBucket: 'seytimstaj.firebasestorage.app',
    measurementId: 'G-W8SZ6FDMY6',
  );
}
